[package]
name = "startin_wasm"
version = "0.5.0"
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
startin = "0.5.*"
wasm-bindgen = "0.2.74"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

